name: Build Android App
on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Build and test
        run: |
          cd ./V2rayNG
          chmod +x ./gradlew
          ./gradlew build
