name: Build Android App

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: V2rayng ID
  
on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      
      - name: cd ./V2rayNG
        run: |
          cd ./V2rayNG
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Build and test
        run: |
          chmod +x ./gradlew
          ./gradlew build
